site_name: QGIS STAC APIs Plugin

repo_url: https://github.com/stac-utils/qgis-stac-plugin
repo_name: GitHub

site_description: QGIS STAC APIs plugin

site_author: Kartoza

nav:
  - Home: 'index.md'
  - Installation: "installation.md"
  - User Guide: "user-guide.md"
  - Development: "development.md"
  - About: "about.md"
  - Changelog: "changelog.md"

theme:
  name: lumen
