site_name: QGIS STAC API Browser

repo_url: https://github.com/stac-utils/qgis-stac-plugin
repo_name: GitHub

site_description: QGIS STAC API Browser

site_author: Kartoza

nav:
  - Home: 'index.md'
  - Installation: "installation.md"
  - User Guide: "user-guide.md"
  - Development: "development.md"
  - About: "about.md"

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  palette:
    scheme: stac
    accent: cyan
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
